### ISSUE TITLE
Some tools missing (in PATH)

### ISSUE THREAD

**Issue by pohutukawa** [tsgkdt/sphinx-plantuml#1]
Unfortunately since the last change of the image my builds on Gitlab-CI keep failing.

I've been using previously make for the build. That's easy enough to work around if not available any more. However, the main problem is that from my Sphinx `conf.py` I'm calling `git` with the `subprocess` module to extract some version information to generate into the output. and I keep getting this exception:

```
Exception occurred:
  File "/usr/local/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

Any ideas on what's wrong, or what path `git` should be in now?

Otherwise: You've done a fine job!

**Comment by tsgkdt** [comment]
In base image (sphinx:3.5.1-alpine), git command is not included.
I'll add git package to this image.

**Comment by tsgkdt** [comment]
now, you can use git command.
git version is 2.8.3.

Thank you for your issue.

**Comment by pohutukawa** [comment]
Awesome, thanks for that. The build works again. Having `make` available would also be nice, as then the config would only need to be made *once* for the job, and not within the `.gitlab-ci.yml` file again. Expecially as Sphinx is quite helpful in setting up the `Makefile`s already. But the main thing is that the `git` command is available again.

**Comment by tsgkdt** [comment]
If this image is useful to you, it's my pleasure.
Thank you for your feedback.
