### ISSUE TITLE
clash of appsdir packagge version with Python 3.6

### ISSUE THREAD

**Issue by pohutukawa** [tsgkdt/sphinx-plantuml#2]
It looks like since the upgrade to Python 3.6 Sphinx in this image is using the `appdirs` package in version 1.4.2. Unfortunately that one is incompatible with Py 3.6, and it needs upgrading to 1.4.3.

For this reason current GitLab CI jobs are failing. Should be an easy fix to get it back into working condition.

Cheers for the good job!

**Comment by tsgkdt** [comment]
Thank you for your feedback.

I think I will upgrade the 'appdirs' version (from 1.4.2 to 1.4.3).
If so, is this problem solved?
If not, I will change python version(previous version 3.5.2)

**Comment by pohutukawa** [comment]
I think the bump of the version for `appdirs` should suffice. It's working nicely on my own Python 3.5 (Ubuntu) system with `appdirs` in 1.4.3. So I'm expecting the problem to be resolved once we're beyond 1.4.2. If you look at the `appdirs` changelog, it mentions some problem with escaping on Py 3.6 to have led to version 1.4.3.

**Comment by tsgkdt** [comment]
https://pypi.python.org/pypi/appdirs/1.4.3

```
appdirs Changelog
appdirs 1.4.3
[PR #76] Python 3.6 invalid escape sequence deprecation fixes
Fix for Python 3.6 support
```

**Comment by pohutukawa** [comment]
Yepp, that's the one :-)

**Comment by tsgkdt** [comment]
Now, docker-hub image was updated.

below is `pip freeze` output .

```
actdiag==0.5.4
alabaster==0.7.10
appdirs==1.4.3
Babel==2.3.4
blockdiag==1.5.3
docutils==0.13.1
funcparserlib==0.3.6
imagesize==0.7.1
Jinja2==2.9.5
MarkupSafe==1.0
nwdiag==1.0.4
olefile==0.44
packaging==16.8
Pillow==4.0.0
Pygments==2.2.0
pyparsing==2.2.0
pytz==2016.10
requests==2.13.0
seqdiag==0.9.5
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.5.3
sphinx-materialdesign-theme==0.0.4
sphinxbootstrap4theme==0.5.0
sphinxcontrib-actdiag==0.8.5
sphinxcontrib-blockdiag==1.5.5
sphinxcontrib-nwdiag==0.9.5
sphinxcontrib-plantuml==0.8.1
sphinxcontrib-seqdiag==0.8.5
webcolors==1.7
```

Also, previous image(python3.5.2, Sphinx1.5.0) was tagged. tsgkadot/sphinx-plantuml:py3.5.2.

**Comment by pohutukawa** [comment]
Sweet, works now with the default image. Thanks, and the quick fix is much appreciated.
